server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://207.154.255.31:5432/auth
    username: postgres
    password: digitalocean
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: u11se03r@gmail.com
    password: tkvb tixr buig chlo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: c8Dboxr7plcET25mrUsxO92IIet4bzpKN8lck51PimMA9Kiukq0Qau1rtA7txc18
  expiration: 3600000